Repository polito/students-app, pull requests merged in 2023-07, with the labels that each got.

#290 feat(messages): show messages in UI
  assets/translations/en.json
  assets/translations/it.json
  lib/ui/components/PersonListItem.tsx
  package-lock.json
  package.json
  src/core/components/HeaderCloseButton.tsx
  src/core/components/RootNavigator.tsx
  src/core/hooks/useScreenReader.ts
  src/core/queries/studentHooks.ts
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/places/components/PlacesNavigator.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/user/components/MessageListItem.tsx
  src/features/user/components/MessageScreenContent.tsx
  src/features/user/components/UserNavigator.tsx
  src/features/user/screens/MessageScreen.tsx
  src/features/user/screens/MessagesScreen.tsx
  src/features/user/screens/NotificationsScreen.tsx
  src/features/user/screens/ProfileScreen.tsx
  src/features/user/screens/UnreadMessagesModal.tsx
  src/utils/dates.ts
  src/utils/messages.ts
Labels: cc-feat

#291 refactor(exams): improve UI
  assets/translations/en.json
  assets/translations/it.json
  lib/ui/components/CtaButton.tsx
  lib/ui/components/ListItem.tsx
  lib/ui/components/RadioGroup.tsx
  lib/ui/types/Input.ts
  package-lock.json
  src/core/components/EventDetails.tsx
  src/core/queries/examHooks.ts
  src/core/themes/dark.ts
  src/core/themes/light.ts
  src/core/types/api.ts
  src/features/teaching/components/ExamCTA.tsx
  src/features/teaching/components/ExamListItem.tsx
  src/features/teaching/components/ExamStatusBadge.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/teaching/screens/ExamQuestionScreen.tsx
  src/features/teaching/screens/ExamRequestScreen.tsx
  src/features/teaching/screens/ExamScreen.tsx
  src/features/teaching/screens/ExamsScreen.tsx
  src/utils/dates.ts
Labels: cc-refactor

#292 fix: handle language preference forwarding to the server
  assets/translations/en.json
  assets/translations/it.json
  package-lock.json
  src/core/components/RootNavigator.tsx
  src/core/contexts/PreferencesContext.ts
  src/core/providers/PreferencesProvider.tsx
  src/core/providers/UiProvider.tsx
  src/core/queries/studentHooks.ts
  src/core/screens/LoginScreen.tsx
  src/features/user/screens/SettingsScreen.tsx
Labels: cc-fix
