Repository polito/students-app, pull requests merged in 2023-11, with the labels that each got.

#348 fix(courses): cannot see previous years virtual classrooms
  src/core/queries/courseHooks.ts
  src/features/courses/screens/CourseLecturesScreen.tsx
  src/features/courses/types/CourseLectureSections.ts
Labels: cc-fix

#349 fix(agenda): mantain agenda screen layout orientation
  src/core/contexts/PreferencesContext.ts
  src/core/providers/PreferencesProvider.tsx
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/agenda/components/AgendaTypeFilter.tsx
  src/features/agenda/queries/agendaHooks.ts
  src/features/agenda/screens/AgendaScreen.tsx
  src/features/agenda/screens/AgendaWeekScreen.tsx
Labels: cc-fix

#356 chore: show the app version
  assets/translations/en.json
  assets/translations/it.json
  src/features/user/screens/SettingsScreen.tsx
Labels: ignore-for-release

#350 fix(tickets): eol is not respected in writing a new ticket
  src/features/tickets/screens/CreateTicketScreen.tsx
Labels: cc-fix

#361 feat(bookings): allow to create and cancel bookings
  assets/translations/en.json
  assets/translations/it.json
  lib/ui/components/CtaButton.tsx
  lib/ui/components/CtaButtonContainer.tsx
  lib/ui/components/EmptyState.tsx
  lib/ui/components/Snackbar.tsx
  lib/ui/components/calendar/Calendar.tsx
  lib/ui/components/calendar/CalendarBody.tsx
  lib/ui/components/calendar/CalendarEvent.tsx
  lib/ui/components/calendar/CalendarHeader.tsx
  lib/ui/icons/faSeat.tsx
  lib/ui/types/Calendar.ts
  lib/ui/types/Theme.ts
  lib/ui/utils/calendar.ts
  package-lock.json
  package.json
  src/App.tsx
  src/core/components/BottomModal.tsx
  src/core/hooks/useBottomModal.ts
  src/core/queries/bookingHooks.ts
  src/core/screens/LoginScreen.tsx
  src/core/themes/light.ts
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/agenda/components/WeekFilter.tsx
  src/features/agenda/screens/AgendaWeekScreen.tsx
  src/features/agenda/screens/BookingScreen.tsx
  src/features/bookings/components/BookingDeskCell.tsx
  src/features/bookings/components/BookingField.tsx
  src/features/bookings/components/BookingListItem.tsx
  src/features/bookings/components/BookingSeatCell.tsx
  src/features/bookings/components/BookingSeatsCta.tsx
  src/features/bookings/components/BookingSlotModal.tsx
  src/features/bookings/components/BookingSlotsStatusLegend.tsx
  src/features/bookings/constant.ts
  src/features/bookings/hooks/useCalculateSeatsDimension.ts
  src/features/bookings/screens/BookingSeatScreen.tsx
  src/features/bookings/screens/BookingSeatSelectionScreen.tsx
  src/features/bookings/screens/BookingSlotScreen.tsx
  src/features/bookings/screens/BookingTopicScreen.tsx
  src/features/places/components/MapNavigator.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/screens/BookingsScreen.tsx
  src/features/services/screens/NewBookingScreen.tsx
  src/features/services/screens/ServicesScreen.tsx
  src/utils/bookings.ts
Labels: cc-feat

#358 feat(places): add EventPlacesScreen, update dep marker, fix place resources
  assets/map-icons/microscope.png
  assets/translations/en.json
  assets/translations/it.json
  lib/ui/components/List.tsx
  lib/ui/components/ListItem.tsx
  lib/ui/types/Theme.ts
  src/core/queries/placesHooks.ts
  src/core/themes/light.ts
  src/features/places/components/MarkersLayer.tsx
  src/features/places/components/PlacesBottomSheet.tsx
  src/features/places/components/PlacesNavigator.tsx
  src/features/places/constants.ts
  src/features/places/screens/EventPlacesScreen.tsx
  src/features/places/screens/PlaceScreen.tsx
  src/features/places/screens/PlacesScreen.tsx
  src/features/places/utils/getCoordinatesBounds.ts
  src/features/teaching/screens/ExamScreen.tsx
Labels: cc-feat

#366 fix: handle cross-tab navigation
  lib/ui/components/PersonListItem.tsx
  package-lock.json
  package.json
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/agenda/screens/BookingScreen.tsx
  src/features/agenda/screens/LectureScreen.tsx
  src/features/bookings/screens/BookingSeatScreen.tsx
  src/features/courses/navigation/CourseNavigator.tsx
  src/features/courses/navigation/CourseSharedScreens.tsx
  src/features/courses/screens/CourseInfoScreen.tsx
  src/features/courses/screens/CourseVideolectureScreen.tsx
  src/features/courses/screens/CourseVirtualClassroomScreen.tsx
  src/features/people/screens/PersonScreen.tsx
  src/features/places/components/MarkersLayer.tsx
  src/features/places/components/PlacesNavigator.tsx
  src/features/places/screens/PlaceScreen.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/teaching/components/ExamStatusBadge.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/teaching/screens/ExamScreen.tsx
  src/features/user/components/MessageScreenContent.tsx
  src/features/user/components/UserNavigator.tsx
  src/features/user/screens/ProfileScreen.tsx
  src/shared/navigation/SharedScreens.tsx
  src/utils/navigation.ts
  src/utils/navigation.tsx
Labels: cc-fix

#369 fix(agenda): fix agenda week calendar
  src/features/agenda/screens/AgendaWeekScreen.tsx
Labels: cc-fix

#367 refactor(agenda): change state management from infinite queries to standard ones
  src/core/queries/studentHooks.ts
  src/features/agenda/queries/agendaHooks.ts
  src/features/agenda/queries/lectureHooks.ts
  src/features/agenda/screens/AgendaScreen.tsx
  src/features/agenda/screens/AgendaWeekScreen.tsx
  src/features/courses/components/CourseListItem.tsx
  src/features/courses/screens/CoursePreferencesScreen.tsx
  src/features/places/hooks/useSearchPlaces.ts
Labels: cc-refactor

#374 fix: prevent url linking when already wrapped into an anchor tag
  src/utils/html.ts
Labels: cc-fix

#382 fix: adjust view for 7-day calendar in calendar.tsx
  lib/ui/utils/calendar.ts
Labels: cc-fix
