Repository polito/students-app, pull requests merged in 2023-12, with the labels that each got.

#377 refactor: prevent navigation to previous weeks in AgendaScreen
  package-lock.json
  src/features/agenda/screens/AgendaScreen.tsx
Labels: cc-refactor

#390 fix(ui): hide tabs when useHideTabs hook is rendered
  src/core/components/RootNavigator.tsx
  src/core/hooks/useHideTabs.ts
Labels: cc-fix

#392 fix(offering): fix offering year formatting, add filter state
  package-lock.json
  package.json
  src/core/queries/offeringHooks.ts
  src/features/offering/navigation/DegreeTopTabsNavigator.tsx
  src/features/offering/types/Degree.ts
Labels: cc-fix

#394 feat(places): add full-text search
  assets/translations/en.json
  assets/translations/it.json
  babel.config.js
  ios/Podfile
  ios/Podfile.lock
  lib/ui/components/EmptyState.tsx
  lib/ui/components/TranslucentTextField.tsx
  lib/ui/components/UnreadBadge.tsx
  lib/ui/components/calendar/CalendarHeader.tsx
  package-lock.json
  package.json
  react-native.config.js
  src/core/components/RootNavigator.tsx
  src/core/components/VideoControls.tsx
  src/core/contexts/PreferencesContext.ts
  src/core/providers/ApiProvider.tsx
  src/core/queries/courseHooks.ts
  src/core/queries/placesHooks.ts
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/agenda/components/AgendaTabs.tsx
  src/features/agenda/types/AgendaItem.ts
  src/features/bookings/screens/BookingSlotScreen.tsx
  src/features/places/components/IndoorMapLayer.tsx
  src/features/places/components/MapControls.tsx
  src/features/places/components/MarkersLayer.tsx
  src/features/places/components/PlaceMarker.tsx
  src/features/places/components/PlacePanel.tsx
  src/features/places/components/PlacesBottomSheet.tsx
  src/features/places/hooks/useGetPlacesFromSearchResult.ts
  src/features/places/hooks/useSearchPlaces.ts
  src/features/places/screens/BuildingScreen.tsx
  src/features/places/screens/EventPlacesScreen.tsx
  src/features/places/screens/FreeRoomsScreen.tsx
  src/features/places/screens/PlaceScreen.tsx
  src/features/places/screens/PlacesScreen.tsx
  src/features/places/types.ts
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/screens/ServicesScreen.tsx
  src/features/surveys/screens/SurveysScreen.tsx
  src/features/teaching/components/ExamStatusBadge.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/teaching/screens/ExamScreen.tsx
  src/features/tickets/components/ChatMessage.tsx
  src/features/tickets/components/TicketListItem.tsx
  src/features/tickets/components/TicketMessagingView.tsx
  src/features/tickets/screens/TicketListScreen.tsx
  src/features/tickets/screens/TicketScreen.tsx
  src/features/user/screens/SettingsScreen.tsx
  src/utils/superjson.ts
Labels: cc-feat

#407 fix(requestScreen): onSubmit if condition
  src/features/teaching/screens/ExamRequestScreen.tsx
Labels: cc-fix

#402 fix: remove user queries without invalidating on logout
  src/core/queries/authHooks.ts
Labels: cc-fix

#412 fix(notifications): explicitly ask for permission on Android if not implicitly granted
  src/core/hooks/messaging.ts
Labels: cc-fix

#411 fix(exams): allow to book exams for courses divided in modules
  package-lock.json
  package.json
  src/core/queries/examHooks.ts
  src/features/teaching/components/ExamCTA.tsx
  src/features/teaching/screens/ExamQuestionScreen.tsx
  src/features/teaching/screens/ExamRequestScreen.tsx
Labels: cc-fix
