Repository polito/students-app, pull requests merged in 2023-10, with the labels that each got.

#303 feat(bookings): allow to read and check-in to existing bookings
  android/app/src/main/AndroidManifest.xml
  assets/translations/en.json
  assets/translations/it.json
  ios/Podfile
  ios/Podfile.lock
  ios/students.xcodeproj/project.pbxproj
  ios/students/Info.plist
  lib/ui/components/CtaButton.tsx
  lib/ui/components/CtaButtonContainer.tsx
  lib/ui/components/ScreenDateTime.tsx
  lib/ui/components/Section.tsx
  lib/ui/types/Theme.ts
  lib/ui/utils/colors.ts
  package-lock.json
  package.json
  src/core/components/EventDetails.tsx
  src/core/hooks/useGeolocation.ts
  src/core/queries/bookingHooks.ts
  src/core/themes/light.ts
  src/features/agenda/components/ExamCard.tsx
  src/features/agenda/screens/BookingScreen.tsx
  src/features/agenda/types/AgendaItem.ts
  src/features/bookings/components/BookingDateTime.tsx
  src/features/services/components/BookingListItem.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/screens/BookingsScreen.tsx
  src/features/services/screens/NewBookingScreen.tsx
  src/features/services/screens/ServicesScreen.tsx
  src/features/teaching/screens/ExamScreen.tsx
Labels: cc-feat

#305 feat(guides): add guide service
  android/app/src/main/res/values/styles.xml
  assets/translations/en.json
  assets/translations/it.json
  ios/Podfile.lock
  lib/ui/components/Badge.tsx
  lib/ui/components/CarouselDots.tsx
  lib/ui/components/ScreenTitle.tsx
  lib/ui/components/Text.tsx
  package-lock.json
  package.json
  src/core/components/HtmlView.tsx
  src/core/contexts/PreferencesContext.ts
  src/core/queries/studentHooks.ts
  src/features/guides/components/GuideFieldListItem.tsx
  src/features/guides/components/GuideSectionListItem.tsx
  src/features/guides/screens/GuideScreen.tsx
  src/features/guides/screens/GuidesScreen.tsx
  src/features/services/components/ServiceCard.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/screens/ServicesScreen.tsx
  src/features/teaching/screens/CourseAssignmentPdfCreationScreen.tsx
Labels: cc-feat

#299 feat(offering): add offering service
  assets/translations/en.json
  assets/translations/it.json
  ios/Podfile.lock
  lib/ui/components/Card.tsx
  lib/ui/components/ListItem.tsx
  lib/ui/components/LoadingContainer.tsx
  lib/ui/components/OverviewList.tsx
  lib/ui/components/PersonListItem.tsx
  lib/ui/components/Text.tsx
  lib/ui/components/TopTabBar.tsx
  lib/ui/components/TouchableCard.tsx
  lib/ui/types/Theme.ts
  src/core/contexts/ApiContext.ts
  src/core/queries/courseHooks.ts
  src/core/queries/offeringHooks.ts
  src/core/queries/studentHooks.ts
  src/core/themes/dark.ts
  src/core/themes/light.ts
  src/features/agenda/components/AgendaNavigator.tsx
  src/features/agenda/queries/agendaHooks.ts
  src/features/agenda/screens/LectureScreen.tsx
  src/features/agenda/types/AgendaItem.ts
  src/features/offering/components/CourseTrailingItem.tsx
  src/features/offering/components/DegreeTrackYear.tsx
  src/features/offering/components/GroupCourses.tsx
  src/features/offering/components/GroupCoursesExpanded.tsx
  src/features/offering/components/StaffListItem.tsx
  src/features/offering/contexts/DegreeContext.ts
  src/features/offering/navigation/DegreeTopTabsNavigator.tsx
  src/features/offering/navigation/OfferingTopTabsNavigator.tsx
  src/features/offering/screens/DegreeCourseGuideScreen.tsx
  src/features/offering/screens/DegreeCourseScreen.tsx
  src/features/offering/screens/DegreeInfoScreen.tsx
  src/features/offering/screens/DegreeJobOpportunitiesScreen.tsx
  src/features/offering/screens/DegreeTracksScreen.tsx
  src/features/offering/screens/Offerings.tsx
  src/features/offering/screens/StaffScreen.tsx
  src/features/places/components/PlacesNavigator.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/screens/CreateTicketScreen.tsx
  src/features/services/screens/ServicesScreen.tsx
  src/features/teaching/components/CourseNavigator.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/teaching/screens/CourseGuideScreen.tsx
  src/features/teaching/screens/CourseInfoScreen.tsx
  src/features/teaching/screens/CoursePreferencesScreen.tsx
  src/features/teaching/screens/CourseVideolectureScreen.tsx
  src/features/teaching/screens/CourseVirtualClassroomScreen.tsx
  src/features/teaching/screens/ExamScreen.tsx
  src/features/teaching/screens/PersonScreen.tsx
  src/features/user/components/MessageScreenContent.tsx
  src/features/user/components/UserNavigator.tsx
  src/features/user/screens/ProfileScreen.tsx
  src/utils/navigation.tsx
  src/utils/offerings.ts
  src/utils/predicates.ts
  src/utils/students.ts
Labels: cc-feat

#308 fix(places): missing places in search
  package-lock.json
  package.json
  src/core/queries/placesHooks.ts
  src/features/places/components/MarkersLayer.tsx
  src/features/places/constants.ts
  src/features/places/hooks/useSearchPlaces.ts
  src/features/places/screens/PlacesScreen.tsx
Labels: cc-fix

#310 chore(onboarding): fix navigation on onboarding completed for iOS devices
  src/core/components/RootNavigator.tsx
  src/core/screens/OnboardingScreen.tsx
Labels: ignore-for-release

#314 fix(auth): fix forgot password link
  src/core/screens/LoginScreen.tsx
Labels: cc-fix

#316 fix(ui): fix app system theme
  src/core/providers/UiProvider.tsx
  src/features/user/screens/SettingsScreen.tsx
Labels: cc-fix

#324 chore(courses): add academic year to extra APSP courses
  ios/Podfile.lock
  package-lock.json
  package.json
  src/features/teaching/components/CourseListItem.tsx
Labels: ignore-for-release

#330 chore(courses): make text URLs included in course notices clickable
  src/features/teaching/screens/NoticeScreen.tsx
Labels: ignore-for-release

#321 fix(courses): improve space usage in course header
  src/features/teaching/components/CourseNavigator.tsx
Labels: cc-fix

#315 fix: refactor translucent text usages to restore functionality in all services
  assets/translations/en.json
  assets/translations/it.json
  ios/Podfile.lock
  ios/students.xcodeproj/project.pbxproj
  lib/ui/components/BottomSheetTextField.tsx
  lib/ui/components/ChatBubble.tsx
  lib/ui/components/FullWidthPicture.tsx
  lib/ui/components/IconButton.tsx
  lib/ui/components/TranslucentTextField.tsx
  package-lock.json
  package.json
  src/features/people/components/HighlightedText.tsx
  src/features/people/components/PersonOverviewListItem.tsx
  src/features/people/components/RecentSearch.tsx
  src/features/people/screens/ContactsScreen.tsx
  src/features/people/screens/PersonScreen.tsx
  src/features/services/components/ServicesNavigator.tsx
  src/features/services/components/TextMessage.tsx
  src/features/teaching/screens/CourseAssignmentUploadConfirmationScreen.tsx
  src/features/tickets/components/AttachmentChip.tsx
  src/features/tickets/components/ChatMessage.tsx
  src/features/tickets/components/MessageTime.tsx
  src/features/tickets/components/MessagingView.tsx
  src/features/tickets/components/TextMessage.tsx
  src/features/tickets/components/TicketAttachmentChip.tsx
  src/features/tickets/components/TicketListItem.tsx
  src/features/tickets/components/TicketMessagingView.tsx
  src/features/tickets/components/TicketStatusInfo.tsx
  src/features/tickets/screens/CreateTicketScreen.tsx
  src/features/tickets/screens/TicketFaqScreen.tsx
  src/features/tickets/screens/TicketFaqsScreen.tsx
  src/features/tickets/screens/TicketListScreen.tsx
  src/features/tickets/screens/TicketScreen.tsx
  src/features/tickets/screens/TicketsScreen.tsx
Labels: cc-fix

#339 fix(agenda): hiding a course does not reflect on agenda immediately
  src/core/hooks/useDownload.ts
  src/core/queries/courseHooks.ts
  src/features/agenda/components/AgendaIcon.tsx
  src/features/agenda/screens/LectureScreen.tsx
  src/features/courses/components/CourseAssignmentListItem.tsx
  src/features/courses/components/CourseDirectoryListItem.tsx
  src/features/courses/components/CourseFileListItem.tsx
  src/features/courses/components/CourseIcon.tsx
  src/features/courses/components/CourseIndicator.tsx
  src/features/courses/components/CourseListItem.tsx
  src/features/courses/components/CourseRecentFileListItem.tsx
  src/features/courses/constants.ts
  src/features/courses/contexts/CourseContext.ts
  src/features/courses/contexts/FilesCacheContext.ts
  src/features/courses/errors/UnsupportedFileTypeError.ts
  src/features/courses/hooks/useCourseFilesCachePath.ts
  src/features/courses/navigation/CourseNavigator.tsx
  src/features/courses/providers/FilesCacheProvider.tsx
  src/features/courses/screens/CourseAssignmentPdfCreationScreen.tsx
  src/features/courses/screens/CourseAssignmentUploadConfirmationScreen.tsx
  src/features/courses/screens/CourseAssignmentUploadScreen.tsx
  src/features/courses/screens/CourseAssignmentsScreen.tsx
  src/features/courses/screens/CourseDirectoryScreen.tsx
  src/features/courses/screens/CourseFilesScreen.tsx
  src/features/courses/screens/CourseGuideScreen.tsx
  src/features/courses/screens/CourseIconPickerScreen.tsx
  src/features/courses/screens/CourseInfoScreen.tsx
  src/features/courses/screens/CourseLecturesScreen.tsx
  src/features/courses/screens/CourseNoticesScreen.tsx
  src/features/courses/screens/CoursePreferencesScreen.tsx
  src/features/courses/screens/CourseVideolectureScreen.tsx
  src/features/courses/screens/CourseVirtualClassroomScreen.tsx
  src/features/courses/screens/CoursesScreen.tsx
  src/features/courses/screens/NoticeScreen.tsx
  src/features/courses/types/Assignment.ts
  src/features/courses/types/CourseLectureSections.ts
  src/features/courses/utils/fs-entry.ts
  src/features/courses/utils/lectures.ts
  src/features/teaching/components/CourseIcon.tsx
  src/features/teaching/components/ExamListItem.tsx
  src/features/teaching/components/TeachingNavigator.tsx
  src/features/teaching/screens/TeachingScreen.tsx
  src/features/teaching/utils/accessibility.ts
  src/features/tickets/components/MessagingView.tsx
  src/features/user/screens/SettingsScreen.tsx
Labels: cc-fix

#343 fix(courses): notices render badly when teachers include custom styles
  src/core/components/HtmlView.tsx
Labels: cc-fix

#340 fix(agenda): manage multiple rooms in agenda exam card
  src/features/agenda/components/ExamCard.tsx
  src/features/teaching/screens/ExamScreen.tsx
Labels: cc-fix

#313 fix(places): restore free rooms search
  ios/Podfile.lock
  src/features/places/hooks/useSearchPlaces.ts
  src/features/places/screens/FreeRoomsScreen.tsx
  src/features/places/screens/PlaceScreen.tsx
  src/features/teaching/screens/ExamScreen.tsx
Labels: cc-fix

#344 fix: onboarding navigation
  src/core/components/RootNavigator.tsx
  src/core/screens/OnboardingModal.tsx
  src/features/teaching/components/TeachingNavigator.tsx
Labels: cc-fix
