Repository polito/students-app, pull requests merged in 2024-05, with the labels that each got.

#481 feat: webmail added
  package-lock.json
  package.json
  src/core/queries/webMailHooks.ts
  src/features/services/screens/ServicesScreen.tsx
Labels: cc-feat

#485 feat(courses): add external links in course info tab
  assets/translations/en.json
  assets/translations/it.json
  package-lock.json
  package.json
  src/features/courses/screens/CourseInfoScreen.tsx
Labels: cc-feat

#487 ci: upgrade pipeline, unify rubies, upgrade to react-native 0.72
  .github/workflows/build.yaml
  .github/workflows/checks.yaml
  .nvmrc
  .ruby-version
  Gemfile
  Gemfile.lock
  __tests__/App-test.tsx
  android/.ruby-version
  android/Gemfile
  android/app/src/main/java/it/polito/students/MainActivity.java
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  ios/.ruby-version
  ios/Gemfile
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/PrivacyInfo.xcprivacy
  ios/fastlane/README.md
  ios/students.xcodeproj/project.pbxproj
  ios/students.xcodeproj/xcshareddata/xcschemes/students dev.xcscheme
  ios/students.xcodeproj/xcshareddata/xcschemes/students.xcscheme
  ios/students/AppDelegate.mm
  jest.config.js
  lib/ui/components/calendar/CalendarEvent.tsx
  metro.config.js
  package-lock.json
  package.json
  src/core/queries/courseHooks.ts
Labels: cc-ci

#491 fix(tickets): fix ticket reply sent multiple times
  src/features/tickets/components/MessagingView.tsx
Labels: cc-fix

#490 fix(courses): fix link indexes
  src/features/courses/screens/CourseInfoScreen.tsx
Labels: cc-fix

#489 fix(ui): fix bottom modal on rotation
  src/core/components/BottomModal.tsx
Labels: cc-fix

#488 fix(webmail): fix unread count as string
  lib/ui/components/UnreadBadge.tsx
  src/features/services/components/ServiceCard.tsx
  src/features/services/screens/ServicesScreen.tsx
Labels: cc-fix

#486 fix(places): max zoom incompatible with tiles max level
  src/features/places/constants.ts
Labels: cc-fix

#492 fix: upgrade mapbox version to address ios xcprivacy file issue
  android/build.gradle
  ios/Podfile.lock
  package-lock.json
  package.json
  src/features/places/components/MapNavigator.tsx
  src/features/places/utils/getCoordinatesBounds.ts
Labels: cc-fix
