Repository polito/students-app, pull requests merged in 2025-01, with the labels that each got.

#564 ci: upgrade actions/upload-artifact to v4 in gh build action
  .github/workflows/build.yaml
Labels: cc-ci

#531 fix(courses): Allow user to choose default files view (by folders/by date)
  assets/translations/en.json
  assets/translations/it.json
  src/core/contexts/PreferencesContext.ts
  src/core/providers/PreferencesProvider.tsx
  src/core/queries/courseHooks.ts
  src/features/courses/navigation/CourseNavigator.tsx
  src/features/courses/navigation/CourseSharedScreens.tsx
  src/features/courses/navigation/FileNavigator.tsx
  src/features/courses/screens/CourseAssignmentsScreen.tsx
  src/features/courses/screens/CourseDirectoryScreen.tsx
  src/features/courses/screens/CourseFilesScreen.tsx
  src/features/user/screens/ProfileScreen.tsx
Labels: cc-fix

#526 fix(login): generate clientID & persist across sessions
  ios/Podfile.lock
  package-lock.json
  package.json
  src/core/providers/ApiProvider.tsx
  src/core/queries/authHooks.ts
Labels: cc-fix

#565 fix: add pip videos on iphone, fix navbar on android
  android/app/src/main/res/values/styles.xml
  package-lock.json
  package.json
  src/core/components/VideoControls.tsx
  src/core/components/VideoPlayer.android.tsx
  src/core/components/VideoPlayer.ios.tsx
Labels: cc-fix

#568 fix(places): fix cross navigation for exams
  src/features/places/components/PlacesListItem.tsx
  src/features/places/components/PlacesNavigator.tsx
  src/features/places/screens/EventPlacesScreen.tsx
  src/features/places/screens/PlaceScreen.tsx
Labels: cc-fix

#569 fix(exams): fix on time exams point
  src/features/transcript/screens/CareerScreen.tsx
Labels: cc-fix

#570 ci: fastlane update + optional sentry
  Gemfile.lock
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: cc-ci

#567 fix(login): remove packages and fix getClientId
  ios/Podfile.lock
  package-lock.json
  package.json
  src/core/queries/authHooks.ts
Labels: cc-fix

#571 fix(notifications): remove courses notifications
  src/features/user/screens/NotificationsScreen.tsx
Labels: cc-fix

#572 build: bump version v1.6.7
  package-lock.json
  package.json
Labels: cc-build
