Repository polito/students-app, pull requests merged in 2025-02, with the labels that each got.

#575 fix(transcript): fix typo language
  assets/translations/en.json
  assets/translations/it.json
Labels: cc-fix

#576 chore: add onCreate method on MainActivity for avoid crashes of react native screen
  android/app/src/main/java/it/polito/students/MainActivity.kt
Labels: ignore-for-release

#577 fix: enable pip on ios
  ios/students.xcodeproj/project.pbxproj
  ios/students/Info.plist
Labels: cc-fix

#579 fix(booking): fix booking seat selection special needs
  src/utils/bookings.ts
Labels: cc-fix

#573 fix(ui): fix grade value, remove upper/lower case and pass standard response value
  src/features/transcript/screens/ProvisionalGradeScreen.tsx
  src/features/transcript/screens/RecordedGradeScreen.tsx
  src/utils/grades.ts
Labels: cc-fix

#578 fix(transcript): add weighted average on career screen and on teaching screen
  assets/translations/en.json
  assets/translations/it.json
  lib/ui/components/ModalContent.tsx
  src/core/components/BottomModal.tsx
  src/features/teaching/screens/TeachingScreen.tsx
  src/features/transcript/components/CareerScreenModal.tsx
  src/features/transcript/screens/CareerScreen.tsx
Labels: cc-fix

#580 fix(courses): enable notifications from courses in previous years
  src/core/hooks/useNotifications.ts
  src/core/queries/courseHooks.ts
  src/features/courses/components/CourseListItem.tsx
  src/features/courses/navigation/CourseNavigator.tsx
  src/features/courses/screens/CourseInfoScreen.tsx
  src/features/teaching/screens/TeachingScreen.tsx
Labels: cc-fix

#581 fix(places): remove floorId param when use Search bar
  src/core/queries/placesHooks.ts
  src/features/places/hooks/useSearchPlaces.ts
Labels: cc-fix

#582 build: bump version
  .github/workflows/build.yaml
  package-lock.json
  package.json
Labels: cc-build

#587 fix(login): added keychain settings for secure storage and updated related API methods
  src/core/providers/ApiProvider.tsx
  src/core/queries/authHooks.ts
  src/utils/keychain.ts
Labels: cc-fix
